# Generated by Django 4.2.4 on 2023-09-26 11:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("image", models.ImageField(upload_to="photos/%Y/%m/%d/")),
            ],
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.CharField(max_length=10)),
                ("currency", models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name="Flower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_fi", models.CharField(max_length=50)),
                ("name_sv", models.CharField(max_length=50)),
                ("name_en", models.CharField(max_length=50)),
                ("latin_name", models.CharField(max_length=100)),
                ("flower_color", models.CharField(max_length=20)),
                (
                    "flower_time_first",
                    models.CharField(
                        choices=[
                            ("1", "Tammikuu"),
                            ("2", "Helmikuu"),
                            ("3", "Maaliskuu"),
                            ("4", "Huhtikuu"),
                            ("5", "Toukokuu"),
                            ("6", "Kesäkuu"),
                            ("7", "Heinäkuu"),
                            ("8", "Elokuu"),
                            ("9", "Syyskuu"),
                            ("10", "Lokakuu"),
                            ("11", "Marraskuu"),
                            ("12", "Joulukuu"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "flower_time_second",
                    models.CharField(
                        choices=[
                            ("13", "-tammikuu"),
                            ("14", "-helmikuu"),
                            ("15", "-maaliskuu"),
                            ("16", "-huhtikuu"),
                            ("17", "-toukokuu"),
                            ("18", "-kesäkuu"),
                            ("19", "-heinäkuu"),
                            ("20", "-elokuu"),
                            ("21", "-syyskuu"),
                            ("22", "-lokakuu"),
                            ("23", "-marraskuu"),
                            ("24", "-joulukuu"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "light_requirement",
                    models.CharField(
                        choices=[("1", "Aurinko"), ("2", "Puolivarjo"), ("3", "Varjo")],
                        max_length=2,
                    ),
                ),
                ("length", models.CharField(max_length=10)),
                ("pot_size", models.CharField(max_length=10)),
                ("adding_source", models.CharField(max_length=30)),
                ("adding_way", models.CharField(max_length=20)),
                ("additional_information", models.CharField(max_length=200)),
                ("new", models.BooleanField(default=True)),
                (
                    "date_added",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 9, 26, 11, 10, 3, 686731, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "photos",
                    models.ManyToManyField(
                        related_name="images", to="kukkatietodb.image"
                    ),
                ),
                (
                    "price",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kukkatietodb.price",
                    ),
                ),
            ],
        ),
    ]
