# Generated by Django 4.2.4 on 2023-11-04 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kukkatietodb", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flower",
            name="date_added",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 4, 11, 46, 4, 934145, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(upload_to="images"),
        ),
    ]
