# Generated by Django 4.2.4 on 2023-11-04 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kukkatietodb", "0002_alter_flower_date_added_alter_image_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flower",
            name="date_added",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 4, 14, 37, 59, 947827, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
